### ISSUE TITLE
Behavior of multiple `plot_structure_2d()` in one `plt.figure`

### ISSUE THREAD

**Issue by sgbaird** [janosh/pymatviz#56]
Not really a bug, just something I noticed. Due to (I think) the following line:
https://github.com/janosh/pymatviz/blob/9c42d7008be76fda757531eda889b83c31018e5d/pymatviz/structure_viz.py#L180

I get the somewhat unintuitive behavior where the plots overlap each other:
```python
from pymatviz.structure_viz import plot_structure_2d
plots = train_structures.apply(plot_structure_2d)
```
![image](https://user-images.githubusercontent.com/45469701/194733953-98010470-5b5b-4e44-a3bf-dfacb6533d6a.png)

`plots` then seems to be empty objects.
```python
plots
```
```python
146     AxesSubplot(0.1981,0.125;0.6288x0.755)
925     AxesSubplot(0.1981,0.125;0.6288x0.755)
1282    AxesSubplot(0.1981,0.125;0.6288x0.755)
Name: structure, dtype: object
```

```python
plots.iloc[0]
```
```python
<AxesSubplot:>
```

By itself works fine:
```python
plot_structure_2d(train_structures.iloc[0])
```

![image](https://user-images.githubusercontent.com/45469701/194734133-174d90ee-74df-41ff-b98a-c01683292e53.png)

**Comment by sgbaird** [comment]
Ok, this is more what I should be going for I think:
```python
import matplotlib.pyplot as plt
fig, axes = plt.subplots(1, 3)
[plot_structure_2d(s, ax=ax) for s, ax in zip(train_structures.tolist(), axes)]
```
![image](https://user-images.githubusercontent.com/45469701/194734382-8c5de04e-5f6f-48b9-9fe2-812799ede840.png)

**Comment by janosh** [comment]
I don't think there's a way for `plot_structure_2d()` to be smart about this since it can't know how many structures there are to plot in total and what the figure's axes layout should be.

> Ok, this is more what I should be going for I think:

Yes, that's the intended usage. There's are 2 somewhat hidden examples of this:

https://github.com/janosh/pymatviz/blob/9c42d7008be76fda757531eda889b83c31018e5d/dataset_exploration/matbench/perovskites/explore_perovskites.py#L45-L49

https://github.com/janosh/pymatviz/blob/9c42d7008be76fda757531eda889b83c31018e5d/assets/_generate_assets.py#L239-L248

Should probably add a multi-axes example to the `plot_structure_2d()` doc string to make it more discoverable.
